telekom/sparrow

.gitignore, pkg/checks/latency.go, pkg/checks/latency_test.go, pkg/sparrow/api.go
The latency check currently uses the wrong time format (µs instead of seconds).
I've changed it to seconds and additionally pulled the timeout assignment out of the go routine since it's unnecessary to assign it every time.
Also added another test case for the run unit tests to test multiple targets.
All unit tests still succeed.
=> fix: latency req timeout calc

internal/helper/retry.go, pkg/config/http.go
Closes #35 
Change time.Timer uses to time.After in http.go and retry.go
=> Refactor: use time.After

README.md, cmd/run.go, docs/sparrow_run.md, pkg/config/config.go, pkg/config/flags.go, pkg/config/validate.go, pkg/config/validate_test.go, pkg/sparrow/run.go
Closes #48 
- Added flags to parse name
- Made DNS valid name mandatory via validation function
- Added some tests to test the most simple validation use cases
The https://**sparrow-cool.de** URL was registered successfully as a target.
https://gitlab.devops.telekom.de/caas/sparrow/registration/-/blob/main/sparrow-cool.de.json?ref_type=heads
=> feat: added dns name to sparrow

README.md, chart/Chart.yaml, chart/README.md, chart/templates/_helpers.tpl, chart/templates/deployment.yaml, chart/templates/secret.yaml, chart/values.yaml
With `v0.2.0` we have introduced the target manager. Therefore we needed to upgrade the helm chart. Here we go... 
- deployed in k8s env
- E2E will fail. It needs to be refactored. Option to diable the target manager will be done with https://github.com/caas-team/sparrow/issues/55
=> feat(helm): add target manager support

README.md, chart/README.md, chart/templates/configmap.yaml, chart/values.yaml, pkg/checks/health.go, pkg/checks/health_test.go
The health check endpoint has been configurable. There is no need to enable or disable it. Therefore the config option has been removed. The endpoint is always enabled as soon as the health check is active.
Additionally, the `enabled` config option of the health and latency check was not used at all. Therefor the option has been removed.
=> feat: always activate health endpoint; rm unnecessary config

pkg/sparrow/gitlab/gitlab.go, pkg/sparrow/gitlab/gitlab_test.go
If the gitlab repo has any other files than `.json`, we get an error.
I've added a filter to only include `.json` files to the file list
I've added a unit test for it.
=> fix: only include json files in gtm file list

chart/README.md, chart/templates/servicemonitor.yaml, chart/values.yaml
Since we're exposing metrics for prometheus, we should also provide a ServiceMonitor, so people who are using the prometheus operator can easily monitor their sparrow instance. 
Closes #52 
This PR adds a serviceMonitor to the helm chart, which can optionally be enabled.
1. Installed sparrow with the default helm chart in a local kind cluster
2. Rolled out kube-prometheus-stack
3. Provisioned a prometheus instance
4. Enabled the serviceMonitor
5. Profit
=> feat: Service Monitor

.github/workflows/ci.yml
Since we build and publish a docker image for every pr and main push, we should do the same thing for the helm chart.
```bash
❯ helm show chart  oci://ghcr.io/caas-team/charts/sparrow --version 0.2.2-commit-3158f2d
Pulled: ghcr.io/caas-team/charts/sparrow:0.2.2-commit-3158f2d
Digest: sha256:4711bb41a28e0f17ab63faa2890a6c5f4f63822b50413ecaa9be94f23cb86f37
```
```yaml
apiVersion: v2
appVersion: commit-3158f2d
description: A Helm chart to install Sparrow
icon: 'https://github.com/caas-team/sparrow/blob/main/docs/img/sparrow.png'
keywords:
- monitoring
maintainers:
- email: f.kloeker@telekom.de
name: eumel8
url: 'https://www.telekom.com'
- email: maximilian.schubert@telekom.de
name: y-eight
url: 'https://www.telekom.com'
name: sparrow
sources:
- 'https://github.com/caas-team/sparrow'
type: …
```
=> feat: package helm chart on push

.github/workflows/prune.yml
Relates to https://github.com/caas-team/sparrow/issues/80
Added a new workflow to prune old images of packages sparrow and charts/sparrow.
The workflow is configured to prune all images older than 7 days that start with 'commit-' or end in 'SNAPSHOT-...' for the sparrow package. 
For the charts/sparrow package it will prune all images older than 7 days that end in 'commit-...'.
It runs daily at midnight (could be changed if wanted).
It is still configured to dry-run just to be sure. This should be changed once we're sure nothings going to break.
I've tested the workflow in dry-run in a fork I made and it worked accordingly.
No stable version or version under 7 days was marked for pruning. …
=> feat: added new workflow to prune old images

pkg/checks/base.go, pkg/checks/base_moq.go, pkg/checks/dns/dns.go, pkg/checks/dns/dns_test.go, pkg/checks/health/health.go, pkg/checks/health/health_test.go, pkg/checks/latency/latency.go, pkg/checks/latency/latency_test.go, pkg/checks/oapi_test.go, pkg/sparrow/controller.go, pkg/sparrow/controller_test.go, pkg/sparrow/handlers_test.go, pkg/sparrow/run.go
Addresses this discussion: https://github.com/caas-team/sparrow/pull/102#discussion_r1484805340
I've removed the result channels of each check. Instead I'm giving the result channel to the `Run` method of each check.
Unit tests succeeded.
=> refactor: use one result channel for all checks

README.md, pkg/config/file.go, pkg/config/file_test.go, pkg/config/http.go, pkg/config/http_test.go, pkg/config/validate.go
Closes #107 
* fix: validate loader interval
* feat: get runtime cfg once if interval is zero
* test: add test cases for the new interval
* fix: file loader run test race condition
Provided a new unit test for both loaders.
=> feat: disable continuous loading of check config

pkg/sparrow/targets/targetmanager.go
The implementation of #101 introduced a bug with its embedded `Config` struct to the `TargetManagerConfig`.
Viper or rather the underlying library mapstructure doesn't unmarshal the embedded fields of the `Config` struct directly in the `TargetManagerConfig` struct. It rather uses the internal struct key of it. So the mapstructure library sees the struct like this:
```go
type TargetManagerConfig struct {
Config Config
Gitlab GitlabTargetManagerConfig `yaml:"gitlab" mapstructure:"gitlab"`
}
```
That means that the startup config currently needs a `Config` key as part of the `targetManager` key which has the general configuration options for the `targetManager`. So an example configuration currently needs to look like this:
```yaml
targetManager:
Config:
checkInterval: 1m …
```
=> fix: missing tags on target manager config field

README.md, chart/Chart.yaml, chart/README.md, chart/values.yaml
To prepare the new release, the chart's `appVersion` needs to be bumped and the docs need to be adjusted.
I've bumped the `appVersion` and adjusted the docs. 
I've also adjusted some of the default values in the chart to be aligned with the configuration options of the docs. The values before were rather confusing to new users.
* chore: bump chart app version
* fix: sparrow config values for chart
* docs: adjust docs to new release
The sparrow deploys successfully with the newest image of the `main` branch.
```sh
$ helm upgrade sparrow ./chart/ -i --set image.tag=commit-ae8c61e -n sparrow --create-namespace
Release "sparrow" does not exist. Installing it now.
NAME: sparrow
LAST DEPLOYED: Wed Feb 21 12:11:14 2024
NAMESPACE: sparrow
STATUS: …
```
=> chore: prepare new release

pkg/sparrow/targets/gitlab.go
The reset timers are unnecessary. The timers carry on automatically and there is no need to reset them. 
Removed the reset call from the timers.
=> Targetmanager doesn't need timer reset

.github/pull_request_template.md, .github/workflows/ci.yml, .github/workflows/prune.yml, .golangci.yaml, .pre-commit-config.yaml, cmd/run.go, go.mod, pkg/api/api.go, scripts/gen-docs/gen-docs.go
I've updated my local external dependencies and suddenly my pre-commit hooks failed.
I saw that as opportunity to also bump the go version and do some general housekeeping of the repository 🙂 
- Bumped go v1.22
- Bumped helm-docs v1.13.0
- Ignoring test files for revive linter
- Resolved revive lint errors
- Formatted and cleaned up workflows
- Made workflows more generic 
- Ref: https://docs.github.com/en/actions/learn-github-actions/variables, https://stackoverflow.com/a/58474340
- Adjusted PR template
=> chore: bump go v1.22 & general housekeeping

go.mod, pkg/checks/base.go, pkg/checks/base_moq.go, pkg/checks/dns/dns.go, pkg/checks/dns/dns_test.go, pkg/checks/health/health.go, pkg/checks/health/health_test.go, pkg/checks/latency/latency.go, pkg/checks/latency/latency_test.go, pkg/checks/traceroute/traceroute.go, pkg/sparrow/controller.go, pkg/sparrow/controller_test.go, pkg/sparrow/targets/gitlab.go
Closes #37 - no need to carry corpses around in the codebase.
See commits. Removed unused err values and ctx values as well from all shutdown functions of the checks, and updated the checkController's shutdown as well (it was never returing an err).
=> Remove unused errors

.github/workflows/ci.yml, .github/workflows/release.yml, .idea/misc.xml
We don't need to depend to MTR doing its mirroring for the image. We can directly push the image here once build and be done with it.
Mirroring is a deferred process, which hasn't been working lately (at least of the sparrow repository). Switching to a push based approach, given the small volume of traffic on this repository, is the simplest solution to move & test quickly.
Changed the CI actions to push the OCI artrifacts to MTR as well.
None needed.
=> Push to MTR directly

.github/workflows/release.yml, chart/Chart.yaml, chart/README.md
The appVersion was false and the helm release job was pushing to a wrong repo.
See commits.
None, seems pretty straightforward.
=> Bump chart's appVersion and fix chart repo on release job

README.md, pkg/checks/latency/latency.go
Referes to https://github.com/caas-team/sparrow/issues/133
The metric `sparrow_latency_duration_seconds` will now be clear before the new duration with label status is exposed.
Dangling metrics that do not show the current status are cleared up.
Additionally, I have introduced two new metrics like @puffitos suggested.
- `sparrow_latency_seconds`
- `sparrow_latency_count` (old `sparrow_latency_count` has been renamed to `sparrow_latency_total_count`)
First run:
```text
sparrow_latency_duration_seconds{status="200",target="https://gitlab.devops.telekom.de"} 0.222653973
sparrow_latency_duration_seconds{status="200",target="https://httpstat.us/random/200,500-504"} 0.711660485
sparrow_latency_duration_seconds{status="418",target="https://yam.telek …
```
=> feat: fix dangaling metrics regading status code

pkg/sparrow/run.go, pkg/sparrow/run_test.go
Closes #148 
This improves the logic in `enrichTargets` to account for any scheme, be that http, https, tcp whatever floats your boat, as long as it's a valid url we're happy.
Parse the url into a `net.Url` so we grab the dns name in an easier way for the dns check.
I've tested it with the latency and dns check enabled using mixed set of targets configured with HTTP and  HTTPS. Seemed to work fine
=> fix: enrich targets now accepts any scheme

pkg/sparrow/targets/manager.go
=> fix: initial registration is now aware of scheme

README.md, pkg/sparrow/targets/manager.go, pkg/sparrow/targets/remote/gitlab/gitlab.go, pkg/sparrow/targets/remote/gitlab/gitlab_test.go, pkg/sparrow/targets/remote/remote.go
Closes #179 
I've added a configuration option to let the user set the branch to use.
Additional to that, I've also improved error handling of response body close errors and refactored the gitlab interactor to use the (*slog.Logger).*Context methods.
[Registration Repository](https://gitlab.devops.telekom.de/tom.vendolsky/sparrow-registration/-/tree/registry)
Logs:
```shell
❯ go run . run --config .tmp/config/start-config.yaml
Using config file: .tmp/config/start-config.yaml
{"time":"2024-09-05T14:28:18.142951065+02:00","level":"INFO","source":{"function":"github.com/caas-team/sparrow/cmd.NewCmdRun.run.func1","file":"/home/installadm/dev/github/sparrow/cmd/run.go","line":89},"msg":"Running sparrow"} …
```
=> feat: add configurable branches for gitlab target manager

CODEOWNERS, NOTICE, pkg/api/errors.go, pkg/checks/health/metrics.go, pkg/checks/latency/metrics.go, pkg/checks/traceroute/check.go, pkg/checks/traceroute/check_test.go, pkg/checks/traceroute/config.go, pkg/checks/traceroute/metrics.go, pkg/checks/traceroute/traceroute.go, pkg/checks/traceroute/traceroute_test.go
To add missing licence headers to the code files as well as updating the `CODEOWNERS` file to remove former employees that are no longer maintaining this repository.
This reflects common [CODEOWNERS](https://chromium.googlesource.com/chromium/src/+/master/docs/code_reviews.md#expectations-of-owners) best practices where the codeowners are only active maintainers of a repository.
=> chore: repo housekeeping

cmd/root.go, docs/sparrow.md, docs/sparrow_run.md
To add a `-c` flag shorthand for the config. We should have this since it's a common flag that is always passed to the CLI and it's cumbersome to always write the whole `--config` flag everytime you want to run sparrow.
Added a shorthand for the `--config` flag.
New help description reflects the new shorthand:
```sh
❯ go run . 
Sparrow is an infrastructure monitoring agent that is able to perform different checks.
The check results are exposed via an API.
Usage:
sparrow [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
run         Run sparrow
Flags:
-c, --config string   config file (default is $HOME/.sparrow.yaml)
-h, --help            help for sparrow
Use …
```
=> feat: add config shorthand

README.md, pkg/sparrow/metrics/config.go, pkg/sparrow/metrics/exporter.go, pkg/sparrow/metrics/metrics.go
Fixes #211 
Added a new option for enabling TLS without custom certs. I changed the config file a bit for this, grouping the tls stuff into their own object. Check the readme for more info
=> fix: allow tls without a custom certificate

pkg/checks/traceroute/traceroute.go
Fixes a crash where, due to a race condition, the err variable would be sometimes overridden to nil just after checking it to be `err != nil` :D. Two lines later, when we call `err.Error()`, we crash since we call the method on a nil pointer. 
=> Hotfix: race condition due to variable shadowing

CHANGELOG.md, README.md, pkg/checks/dns/dns.go
The DNS check was the only one not fully using camel case in the API response.
I added JSON tags to the DNS result struct.
=> fix: camel case for dns result
